export const MICROSERVICES_CLIENTS = {
  USERS_SERVICE: 'USERS_SERVICE',
  PRODUCTS_SERVICE: 'PRODUCTS_SERVICE',
  ORDERS_SERVICE: 'ORDERS_SERVICE',
  PAYMENTS_SERVICE: 'PAYMENTS_SERVICE',
  PRODUCT_REDIS_CLIENT: 'PRODUCT_REDIS_CLIENT',
};
